### PR TITLE
GL matrix features

### PR DESCRIPTION
**Pull request by kalwalt**
From issue #5 and #14 
this PR add:
- transMatToGLMat()
- arglCameraViewRHf()
 and change the getCameraMatrix():

 ```diff
 - ARController.prototype.getCameraMatrix = function (nearPlane, farPlane) {
 -     return artoolkitXjs._arwGetProjectionMatrix(nearPlane, farPlane);

 + ARController.prototype.getCameraMatrix = function (nearPlane = 0.1, farPlane = 1000) {
 +    return artoolkitXjs.getProjectionMatrix(nearPlane, farPlane);
```

### CODE REVIEW

**Comment by ThorstenBux** [comment]
As for that, I've forked WebGLStudio and integrated artoolkitX.js into WebGLStudio so that you can create 3D projects inside WebGLStudio if one like to do so. Was thinking about hosting that as a kind of AR Studio solution. What do you think about that?

**Comment by kalwalt** [comment]
> As for that, I've forked WebGLStudio and integrated artoolkitX.js into WebGLStudio so that you can create 3D projects inside WebGLStudio if one like to do so. Was thinking about hosting that as a kind of AR Studio solution. What do you think about that?

This is super! Don't need to ask, i think it is a great idea :smile: 
Anyway, about this PR i will wait for #23 , there are probably commits that we don't need. so I don't know if it would make sense to merge it.

**Comment by kalwalt** [comment]
@ThorstenBux I can't get litegl.js to work together with ARtoolkitX.js, it seems to me to be close, but when I try to fill the model with a transformation matrix, nothing is seen anymore...
Probably it is needed some other steps.

**Comment by kalwalt** [comment]
the view matrix for litegl is a 4X4 matrix  (a 16 float values array)  that one instead from getCameraMatrix() is a 128 float values array. Does It needs a conversion?

**Comment by kalwalt** [comment]
i'm closing this PR because the cahnges are already in the master with #23. For the `litegl.js` example i will see in another PR.

**Comment by kalwalt** [comment]
At this moment in master branch getCameraMatrix(getProjectionMatrix) get me the right number of values 16 and not 128,

**Pull request closed without merging**
