### PR TITLE
artoolkitx.js lib (Debug) build and small modifcations

### PR DESCRIPTION
**Pull request by kalwalt**
# Testing ArtoolkitX.js and improvements
## Building infos
if you want to try the build process clone this branch https://github.com/kalwalt/artoolkitX.js/tree/testing-branch  enter in the `Source` folder and in a terminal console run `./build.sh --dev` : the script should start doing some checks and to download the [ArtoolkitX](https://github.com/augmentmy-world/artoolkitX.js) repo or you can choose another location and setting up a **env** variable ( ARTOOLKITX_HOME ).
If you have a problem report here or in the [tracker issue](https://github.com/augmentmy-world/artoolkitX.js/issues).

## Example to test
At the moment there are not so many examples, because not all the functions are implemented.
Try the simple_video and simple_video_hiro example. 

## Function to be implemented
I will try to make a list of features and functions that must be implemented. For now we want  only the basic functionality...
- [ ] transformation matrix and GL transformation matrix
- [ ] detectMarker, getMarker, debugMarker
- [ ] Multi markers?
The list needs to be updated...

@ThorstenBux @augmentmy-world artoolkitx.js lib is ready ( debug version) but i receive this error: 

```js
Live reload enabled.
Navigated to http://127.0.0.1:3000/Examples/simple_image.html
artoolkitx.js:1777 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
(anonymous) @ artoolkitx.js:1777
Promise.then (async)
createWasm @ artoolkitx.js:1774
Module.asm @ artoolkitx.js:1807
(anonymous) @ artoolkitx.js:7100
(anonymous) @ artoolkitx.js:7882
artoolkitx.js:1778 falling back to ArrayBuffer instantiation
(anonymous) @ artoolkitx.js:1778
Promise.then (async)
createWasm @ artoolkitx.js:1774
Module.asm @ artoolkitx.js:1807
(anonymous) @ artoolkitx.js:7100
(anonymous) @ artoolkitx.js:7882
artoolkitX.api.js:62 Uncaught (in promise) TypeError: artoolkitXjs.initialiseAR is not a function
    at ARController.start (artoolkitX.api.js:62)
    at simple_image.html:25
ARController.start @ artoolkitX.api.js:62
(anonymous) @ simple_image.html:25
Promise.then (async)
(anonymous) @ simple_image.html:25
```
This happens when i try the `test.html` and `simple_image.html` example
Probably some modifcation is required in the artoolkitx.api.js file.

### CODE REVIEW

**Comment by kalwalt** [comment]
maybe is related to this issue: https://github.com/artoolkitx/jsartoolkit5/issues/40

**Comment by kalwalt** [comment]
Maybe initialiseAR is not yet implemented in [ARX_js.h](https://github.com/artoolkitx/artoolkitx/blob/emscripten/Source/artoolkitx.js/ARX_js.h)?

**Comment by ThorstenBux** [comment]
why did you move the libs from SDK into the example?

**Comment by kalwalt** [comment]
@ThorstenBux I have to re-check this but if i remember right, i have problems loading the lib. I will come back on this sooner.

**Comment by kalwalt** [comment]
@ThorstenBux i moved the libs in examples folder because i didn't compilde the lib with the build script. It faild everytime i tried, with messages errors like can't find OpneGl libs and other libs. Instead i used the cmake gui with the emscripten option, but wasn't so simple.
Also another note: 
initialiseAR in test.html
 https://github.com/augmentmy-world/artoolkitX.js/blob/cbeaccb51f195d8fa711814224334abbd98c5a30/Examples/test.html#L7
is not defined in
https://github.com/artoolkitx/artoolkitx/blob/emscripten/Source/artoolkitx.js/ARX_js.h
nor in artoolkit.js and artoolkitX.api.js

**Comment by ThorstenBux** [comment]
Can you try and build with ```./build.sh --dev``` please

I haven't setup the actual build which would be pulling the prebuild dependencies because the emscripten branch isn't merged into artoolkitX. I should probably fork the repo and merge it and create my own releases to have the dependencies ready for download.

**Comment by kalwalt** [comment]
@ThorstenBux i want to re-build the lib but i don't remember the successfull process i used time ago.
if i run as you suggest:
```shell
./build.sh --dev
bad option --dev
Usage: build.sh [--debug] (macos | windows | ios | linux | android | linux-raspbian | emscripten | docs)... [tests] [examples] [unity]
```
if i run instead:
```shell
./build.sh emscripten
Building emscripten
-- Using single-configuration CMake generator.
OpenCV_LIBS=
-- Could NOT find OpenCV (missing: OpenCV_LIBS OpenCV_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:176 (message):
  OpenCV not found, will build without 2D tracker


-- Defined: ARX_TARGET_PLATFORM_EMSCRIPTEN=1
-- Could NOT find OpenGLES2 (missing:  OPENGLES2_LIBRARIES OPENGLES2_INCLUDE_DIR)
/usr/usr/local/opt/local
-- Could NOT find OpenGL3 (missing: OpenGL3_LIBRARIES OpenGL3_INCLUDE_PATH) 
-- Opting for desktop OpenGL. Set ARX_GL_PREFER_EMBEDDED to change.
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindJPEG.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ARX/ARVideo/CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/walter/kalwalt-github/artoolkitx/Source/CMakeFiles/CMakeOutput.log".
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/walter/emsdk/node/8.9.1_64bit/bin/node" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/walter/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake at /home/walter/kalwalt-github/artoolkitx/Source/build-em
```
note that i have all the libs, it seems that cmake fails to find the libs/pkgs.
i'm on a Ubuntu machine, so Linux based OS.

**Comment by ThorstenBux** [comment]
```./build.sh``` is the build option of artoolkitX.js you seem to be using it from artoolktiX directory.

I pushed a small change but please make sure you are running build.sh from ./Source not from artoolkitX root

**Comment by ThorstenBux** [comment]
I see the issue now. I'm working on it

**Comment by kalwalt** [comment]
@ThorstenBux I realized that was starting the `./build.sh` from the wrong location, i updated my branch, thank you!

**Comment by ThorstenBux** [comment]
Is it working for you? Because it isn’t for me and I can’t figure out why. I’m a bit puzzled by that because it worked a few weeks back and I didn’t change anything as far as I can remember.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
> Is it working for you? Because it isn’t for me and I can’t figure out why. I’m a bit puzzled by that because it worked a few weeks back and I didn’t change anything as far as I can remember.

Unfortunately not see the log:

 ```shell
./build.sh --dev
+ test 1 -gt 0
+ case "$1" in
+ DEV=1
+ shift
+ test 0 -gt 0
+ '[' 1 ']'
+ locate_artkX
+ '[' '!' -f /home/walter/kalwalt-github/artoolkitX.js/Source/Extras/artoolkitx/LICENSE.txt ']'
+ '[' -z /home/walter/kalwalt-github/artoolkitx ']'
+ '[' -f /home/walter/kalwalt-github/artoolkitX.js/Source/Extras/artoolkitx/LICENSE.txt ']'
+ cd /home/walter/kalwalt-github/artoolkitx/Source
+ '[' ']'
+ ./build.sh emscripten
Building emscripten
-- Using single-configuration CMake generator.
OpenCV_LIBS=
-- Could NOT find OpenCV (missing: OpenCV_LIBS OpenCV_INCLUDE_DIR) 
CMake Warning at CMakeLists.txt:176 (message):
  OpenCV not found, will build without 2D tracker


-- Defined: ARX_TARGET_PLATFORM_EMSCRIPTEN=1
-- Could NOT find OpenGLES2 (missing:  OPENGLES2_LIBRARIES OPENGLES2_INCLUDE_DIR)
/usr/usr/local/opt/local
-- Could NOT find OpenGL3 (missing: OpenGL3_LIBRARIES OpenGL3_INCLUDE_PATH) 
-- Opting for desktop OpenGL. Set ARX_GL_PREFER_EMBEDDED to change.
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find JPEG (missing: JPEG_LIBRARY JPEG_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindJPEG.cmake:30 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  ARX/ARVideo/CMakeLists.txt:13 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/walter/kalwalt-github/artoolkitx/Source/CMakeFiles/CMakeOutput.log".
shared:ERROR: Configure step failed with non-zero return code: 1.  Command line: cmake -DCMAKE_CROSSCOMPILING_EMULATOR="/home/walter/emsdk/node/8.9.1_64bit/bin/node" .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=/home/walter/emsdk/emscripten/1.38.31/cmake/Modules/Platform/Emscripten.cmake at /home/walter/kalwalt-github/artoolkitx/Source/build-em

```
I'm testing on a Ubuntu machine, i found that cmake don't find my Opencv libs because my libs are in `/usr/lib/x86_64-linux-gnu ` the OpenCV cmake module is not aware of:

https://github.com/artoolkitx/artoolkitx/blob/68245e9edfea9c86585fc29572f8a8a75e0df1bc/Source/cmake/FindOpenCV.cmake#L16-L26

Maybe something similar for the other pkgs?

**Comment by kalwalt** [comment]
Does it possible to set up ENV variables for cmake?

**Comment by kalwalt** [comment]
I think my comment https://github.com/augmentmy-world/artoolkitX.js/pull/2#issuecomment-517925610
is not correct, my OpenCV includes are in `/usr/include/opencv2` that i think it is correct.

**Comment by kalwalt** [comment]
considering this [comment](https://github.com/augmentmy-world/artoolkitX.js/issues/1#issuecomment-520224946) build process seems to work. The only working example is now `simple_video_hiro.html`,
i would understand why the other examples does not work. More infos later...

**Comment by kalwalt** [comment]
`simple_video.html` also works. Instead i added the wasm include to `simple_image.html` and a `ar1.setLogLevel(0);` it fails at the `start` function at `var success = artoolkitXjs.initialiseAR();`  the log message is:

```shell
Live reload enabled.
simple_image.html:41 TypeError: Cannot read property 'ARW_TRACKER_OPTION_SQUARE_DEBUG_MODE' of undefined
    at ARController.enableDebugMode (artoolkitX.api.js:425)
    at ARController.debugSetup (artoolkitX.api.js:232)
    at ARController.setLogLevel (artoolkitX.api.js:448)
    at simple_image.html:29
```

**Comment by kalwalt** [comment]
`simple_video-multi-patt.html` can not load the markers?
artoolkitX.api.js:285 Uncaught (in promise) Error loading multi marker: TypeError: ARController[_ajax] is not a function

**Comment by kalwalt** [comment]
Same error with `simple_video-multi-barcode.html ` the ajax function needs a check. Added to my to do list.

**Comment by ThorstenBux** [comment]
Let me know when you think we should merge this. The changes are summing up and I like to keep PRs small if possible. :)

**Comment by kalwalt** [comment]
I'm considering to close this PR without merging It and reopen another one  with less commits: infact i canceled and i re-add the SDK/lib in the examples and also the PR was intended to test and to make some simple examples working.

**Comment by kalwalt** [comment]
Maybe it is not necessary to close this PR. I force-pushed the last commit to keep only the changes relative to the examples. Anyway the `simple_video-multi-barcode.html` and `simple_video-multi-patt.html` are not working for me i receive always this error:

```js
artoolkitX.api.js:294 Uncaught (in promise) Error loading multi marker: TypeError: ARController[_ajax] is not a function
```
I didn't look at too much at this issue because more interested to understand and studying the code and the new ArtoolkitX API: Very interesting the ARTrackable class and i saw that the transformation data are already available when the marker is detected. I'd like to restore the getMarkerInfo as was in [jsartoolkit5](https://github.com/artoolkitx/jsartoolkit5/blob/b2a6c7529777999030773e02266799390482ba2a/emscripten/ARToolKitJS.cpp#L688) ( and so you can get position, vertex and other useful data) but maybe there is already a function like this or similar?

**Comment by kalwalt** [comment]
Another thing: in the simple_video example the `barcodeId=36` does not match that in the video `output_4.mp4`  if you remember what id is i can change the code. Or i can upload another video with a barcodeId number 36.

**Comment by ThorstenBux** [comment]
36 is this one: https://github.com/artoolkit/artoolkit5/blob/master/doc/patterns/Matrix%20code%203x3%20(72dpi)/36.png

But hard to find the one that is used in the video 
https://github.com/artoolkit/artoolkit5/tree/master/doc/patterns/Matrix%20code%203x3%20(72dpi)
Lists all of them :)

**Comment by ThorstenBux** [comment]
I won't look into the ajax issue at the moment. It might be an issue with multi pattern. If that becomes a blocker for you let me know.

**Comment by kalwalt** [comment]
> But hard to find the one that is used in the video

Yes, the link you give me is only for barcode 3X3 Matrix that one in the video is 5X5 Matrix, i will try with the `check_id` app,

> I won't look into the ajax issue at the moment. It might be an issue with multi pattern. If that becomes a blocker for you let me know.

Yes , I agree with you. This was more a note for the future.

**Comment by kalwalt** [comment]
I found one of the Barcode Id thanks to the `artoolkitx_check_id` app i was able to read the id. I had to build ArtoolkitX project under Ubuntu 18.04, some of the libs required are not in the standard repository, but at the end the built was successfull. 
Another issue to look at in the future: I added a `arController.debugSetup()` but this not display the lumaVideo but only replicating the original videoFrame.
Schermata del 2019-08-15 15-55-10
Anyway i'm fine with this PR, tell me what do you think.

**Comment by kalwalt** [comment]
It wiil be nice to write a README.md file to add to the project, just to add some basic infos to build the project, in case someone else is interested.

**Comment by ThorstenBux** [comment]
Luma video is the one on the bottom under the first video. It is 4 times because it only requires 1/4 of the pixels and I didn't bother with scaling it to original size. Also, it is drawing to canvas with the same size as video size.

**Comment by kalwalt** [comment]
@ThorstenBux ok thank you for the clarification. But should be in B/W also the canvas on the right? The debugSetup() ?

**Comment by ThorstenBux** [comment]
I know what you mean. I think it shouldn’t duplicated the video but I don’t recall right now why it does. I think one is the video frame and the other would be the overlay canvas including the video frame but it has been some time since I looked into that tbh.

We should start noting issues in an organized way. I’ve added a board in the projects tab and added you as collaborator. I hope that gives you access to that board.

**Comment by kalwalt** [comment]
thank you @ThorstenBux  to add me to the project; i will start to make a list of issues, there are many things to fix and to develop.  I will add a simple Readme file and after i think we can close this PR.

**Comment by ThorstenBux** [comment]
I thank you ☺ for getting me back into this. I believe this base has potential for webAR but being on my own I didn’t drive it further.

**Comment by kalwalt** [comment]
yes indeed,  ArtoolkitX.js :100: :1st_place_medal: , I am very curious for the 2d and NFT tracking, started a [branch](https://github.com/kalwalt/artoolkitX.js/tree/NFT-feature) on my repo, i hope to be able to develop some decent code...

**Comment by kalwalt** [comment]
@ThorstenBux Should we update the ArtoolkitX.js version in package.json ?

https://github.com/kalwalt/artoolkitX.js/blob/117154b973f112d607c01446a58738a4d381cc46/package.json#L3

`artoolkitXjs.getARToolKitVersion()` return `1.0.2 `
What is your idea on the versioning?

**Comment by ThorstenBux** [comment]
Any way you like. I haven’t cared about versioning much lately and so far I don’t know of anyone using it so we are free to do versioning I think.

**Comment by kalwalt** [comment]
I realized that i missed an ` artoolkitx.js` lib in the Source folder, this was due to my first tests and i forgot to delete it. 
About the version convention to use i will open another issue, for now i think we can let `1.0.0` in package.json because it is the first one that officially can be build.
After this we can merge it. i realized that as collaborator I am enabled to do the merge, but want to ask before.

**Pull request merged**
