### PR TITLE
adjusted build.sh

### PR DESCRIPTION
**Pull request by 0110110101100010**
Building with the Windows subsystem for Linux (Ubuntu) did not work using --dev.

### CODE REVIEW

**Comment by kalwalt** [comment]
Hi @0110110101100010 I think nobody has tried with Windows, but maybe @ThorstenBux did in the past. I would test your script on my Linux machine and i will let you know if i find some issues.

**Comment by kalwalt** [comment]
@0110110101100010 i tested it works perfectly under Linux Ubuntu 18.04 though i can not test with Mac OS @ThorstenBux  maybe if you have time...

**Comment by 0110110101100010** [comment]
@kalwalt I tried with a macOS device. Worked.

**Comment by kalwalt** [comment]
@0110110101100010 Perfect!

**Comment by kalwalt** [comment]
@ThorstenBux have you tried? i think that we can merge it.

**Comment by ThorstenBux** [comment]
Thanks @0110110101100010 and @kalwalt. I've merged it

**Pull request merged**
